### ISSUE TITLE
Error when running the pbmc_1k_v3_fastq example: "No values given for wildcard 'target'."

### ISSUE THREAD

**Issue by ainefairbrother** [Mayrlab/scUTRquant#65]
I set up the conda environment and installed the package precisely as detailed. However, upon running `cd scUTRquant/examples/pbmc_1k_v3_fastq/; sh download.sh` followed by `snakemake --use-conda --configfile examples/pbmc_1k_v3_fastq/config.yaml`, I get the following error: 

```
[INFO] Loading sample data...
[INFO] Loaded 1 samples.
WildcardError in line 238 of scUTRquant/Snakefile:
No values given for wildcard 'target'.
  File "scUTRquant/Snakefile", line 238, in <module>
```

**Comment by mfansler** [comment]
Thanks for reporting your issue! I'd be happy to help troubleshoot this with you.

Unfortunately, I am unable to recreate this error at this time (using Snakemake v7.32.4). Would you mind adding some additional details, as well as including the full input and output of a shell session where you are attempting to run this?

## Requested Additional Details

- OS
- terminal (e.g., VSCode, macOS Terminal)
- shell (e.g., bash, zsh)
- output of `conda info` (or `mamba info`)
- Snakemake version
- contents of `scUTRquant/examples/pbmc_1k_v3_fastq/config.yaml` file

Feel free to mask any personal details (e.g., user) in the outputs.

**Comment by ainefairbrother** [comment]
Hi, now that you highlight the Snakemake version, I've found it to be an issue with this - I've updated Snakemake now no longer get this error. Thanks for getting back to me.

**Comment by mfansler** [comment]
Glad it worked out!

Would you mind reporting here what version of Snakemake that was initially tried? This would be helpful to ensure we are providing correct recommendations to users. Thanks!
