### ISSUE TITLE
Downloading scripts fail

### ISSUE THREAD

**Issue by jpintar** [Mayrlab/scUTRquant#76]
The whitelist URLs appear to have changed again, so [`download_10X_whitelists.sh`](https://github.com/Mayrlab/scUTRquant/blob/main/extdata/bxs/download_10X_whitelists.sh) fails with a 404 error. I've added a PR 
(#75) with updated URLs, but perhaps it would make sense to copy the whitelists into this repository directly to avoid future changes like this.

Data-set downloads from `https://cf.10xgenomics.com` also fail because of an expired certificate. In the short term, that could be fixed by adding `--no-check-certificate` to `wget`, but I'm not sure whether that's the best way to go...

**Comment by jpintar** [comment]
I just tested the data-set downloads again, and they're working without problems, so whatever the certificate errors I was getting were about, the issue was transient. Sorry for the false alarm, and thanks for looking into it!

**Comment by mfansler** [comment]
Sounds good! I'll close this then as resolved by #75. Thanks again for updating the links.
