### ISSUE TITLE
Number of detected cells much lower than expected

### ISSUE THREAD

**Issue by MathieuBo** [Mayrlab/scUTRquant#95]
Hi there! 

Thanks for sharing this great package. 
After running on bam files from mouse brain data (10xv3 multiome), I am surprised to only obtain a small number of cells (~10k) whilst I have about 150k post-qc from cellranger. I used the preprocessed target dataset.
Is such a difference expected?
I have slightly edited the ```min_umi``` parameter to include more cells but I am expected cells to have a larger count anyway. 

Any help will be greatly appreciated!
Best, 
Mathieu

**Comment by mfansler** [comment]
Thanks for the interest, Mathieu!

While we haven't characterized this ourselves, it is expected that single-cell versus single-nucleus assays will have a substantial difference in read mapping rates to the 3'end of transcripts. Last I checked, when CellRanger quantifies genes for single-nucleus (e.g., Multiome), it uses the whole gene locus (including introns) to boost sensitivity. Many of these reads will be the result of internal priming of A-rich regions in primary transcripts, and our pipeline will ignore these - we only count reads that fall within cleavage-adjacent regions. So, we would expect a drop in UMI counts per cell.

With that in mind, I would not rely on setting too high a `min_umi` count. Instead, if you already have a list of cells that passed QC through CellRanger, I would create a `cell_annots` file and use the `exclude_unannotated_cells: true` option to simply defer to the QC that CellRanger already did. If you use that option, you can simply set `min_umi: 0`.

Another technical possibility is that something could be wrong with the sample sheet. For example, if you have 150K cells, then that presumably should consist of multiple libraries. If one listed all of these as a single sample, it would result in cells with the same barcode across libraries being merged. It might also be useful to check the output of the UMI-barcode rank plot(s) in the `qc/umi_count` outputs.

Hope that helps! Please feel free to reach out with any more questions.

**Comment by mfansler** [comment]
Another possibility is that the barcode whitelist isn't correctly matched to the input.

**Comment by MathieuBo** [comment]
Many thanks for the feedbacks and ideas! 
I think the barcode whitelist might be the problem, as when I provided a ```cell_annots``` the software couldn't match the cells. I am running now with a new barcode whitelist. I'll let you know how it goes.

Thanks!

**Comment by MathieuBo** [comment]
Changing the barcode whitelist did the trick! I created a PR with the link to the new file. Thanks for your help!

**Comment by mfansler** [comment]
Resolved with #96
